import os
from typing import List
from pydantic_settings import BaseSettings, SettingsConfigDict
from pydantic import Field

class Settings(BaseSettings):
    model_config = SettingsConfigDict(extra='ignore')

    OPENAI_API_KEY: str | None = None
    ANTHROPIC_API_KEY: str | None = None
    GEMINI_API_KEY: str | None = None
    OPENAI_BASE_URL: str | None = None
    REPLICATE_API_KEY: str | None = None

    NVIDIA_API_KEY_GLM: str | None = None
    NVIDIA_API_KEY_KIMI: str | None = None
    NVIDIA_BASE_URL: str = "https://integrate.api.nvidia.com/v1"

    CONSENSUS_ENABLED: bool = False
    ORCHESTRATION_ENABLED: bool = True
    ORCHESTRATION_QUALITY_THRESHOLD: float = 6.5
    ORCHESTRATION_MAX_DEBATE_ROUNDS: int = 2
    ORCHESTRATION_CONFIDENCE_TARGET: float = 7.5

    AGENT_TIMEOUT_SECONDS: int = 300

    IS_DEBUG_ENABLED: bool = False
    DEBUG_DIR: str = ""
    PROMPT_REPORTS_ENABLED: bool = False
    
    LOCAL_ASSET_DIR: str = os.path.join(os.path.dirname(__file__), "local_assets")
    LOCAL_ASSET_BASE_URL: str = "http://127.0.0.1:7001"

    IS_PROD: bool = False
    ALLOWED_ORIGINS: str = ""

    SCREENSHOT_TIMEOUT_MS: int = 30000
    SCREENSHOT_VIEWPORT_WIDTH_DESKTOP: int = 1280
    SCREENSHOT_VIEWPORT_HEIGHT_DESKTOP: int = 832
    SCREENSHOT_VIEWPORT_WIDTH_MOBILE: int = 375
    SCREENSHOT_VIEWPORT_HEIGHT_MOBILE: int = 812

settings = Settings()

NUM_VARIANTS = 4
NUM_VARIANTS_VIDEO = 2

# Expose settings for backwards compatibility
OPENAI_API_KEY = settings.OPENAI_API_KEY
ANTHROPIC_API_KEY = settings.ANTHROPIC_API_KEY
GEMINI_API_KEY = settings.GEMINI_API_KEY
OPENAI_BASE_URL = settings.OPENAI_BASE_URL
REPLICATE_API_KEY = settings.REPLICATE_API_KEY
NVIDIA_API_KEY_GLM = settings.NVIDIA_API_KEY_GLM
NVIDIA_API_KEY_KIMI = settings.NVIDIA_API_KEY_KIMI
NVIDIA_BASE_URL = settings.NVIDIA_BASE_URL
CONSENSUS_ENABLED = settings.CONSENSUS_ENABLED
ORCHESTRATION_ENABLED = settings.ORCHESTRATION_ENABLED
ORCHESTRATION_QUALITY_THRESHOLD = settings.ORCHESTRATION_QUALITY_THRESHOLD
ORCHESTRATION_MAX_DEBATE_ROUNDS = settings.ORCHESTRATION_MAX_DEBATE_ROUNDS
ORCHESTRATION_CONFIDENCE_TARGET = settings.ORCHESTRATION_CONFIDENCE_TARGET
AGENT_TIMEOUT_SECONDS = settings.AGENT_TIMEOUT_SECONDS
IS_DEBUG_ENABLED = settings.IS_DEBUG_ENABLED
DEBUG_DIR = settings.DEBUG_DIR
PROMPT_REPORTS_ENABLED = settings.PROMPT_REPORTS_ENABLED
LOCAL_ASSET_DIR = settings.LOCAL_ASSET_DIR
LOCAL_ASSET_BASE_URL = settings.LOCAL_ASSET_BASE_URL
IS_PROD = settings.IS_PROD
ALLOWED_ORIGINS = settings.ALLOWED_ORIGINS
