import json
import logging
import traceback
from typing import Dict, Any, Optional

import openai
from pydantic import BaseModel, Field

from llm import Llm

logger = logging.getLogger(__name__)

class QualityScoreResult(BaseModel):
    score: int = Field(description="Score out of 100 for visual fidelity and code quality.")
    feedback: str = Field(description="Brief feedback explaining the score and any missing requirements.")

async def evaluate_code_quality(
    code: str,
    original_prompt: str,
    model: Llm,
    api_key: str,
    base_url: Optional[str] = None
) -> QualityScoreResult:
    """
    Evaluates the generated code against the original prompt.
    Returns a score out of 100 and brief feedback.
    """
    if not api_key:
        logger.warning("No API key provided for quality scorer, skipping evaluation.")
        return QualityScoreResult(score=100, feedback="Skipped evaluation (no API key).")

    system_prompt = (
        "You are an expert Staff Frontend Engineer acting as a Quality Assurance Reviewer. "
        "Your job is to review HTML/React/Tailwind code generated by AI models and score it based on: "
        "1. Visual Fidelity (layout, spacing, alignment, responsiveness). "
        "2. Aesthetics (color palette, typography, micro-interactions). "
        "3. Requirement Satisfaction (does it fulfill the original prompt?). "
        "Score from 0 to 100. Return valid JSON containing 'score' (int) and 'feedback' (str)."
    )

    user_message = f"Original Prompt:\n{original_prompt}\n\nGenerated Code:\n```\n{code}\n```"

    try:
        client = openai.AsyncOpenAI(api_key=api_key, base_url=base_url)
        
        # Use an affordable/fast model for evaluation, e.g. gpt-4o-mini
        eval_model = "gpt-4o-mini" if "gpt" in model.value else model.value
        
        response = await client.chat.completions.create(
            model=eval_model,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_message}
            ],
            response_format={"type": "json_object"},
            temperature=0.1,
            max_tokens=200
        )
        
        result_text = response.choices[0].message.content or "{}"
        data = json.loads(result_text)
        
        score = int(data.get("score", 100))
        feedback = data.get("feedback", "No feedback provided.")
        
        return QualityScoreResult(score=score, feedback=feedback)
    except Exception as e:
        logger.error(f"Error during code quality evaluation: {e}")
        logger.debug(traceback.format_exc())
        return QualityScoreResult(score=100, feedback="Evaluation failed. Automatically passing.")
